### ISSUE TITLE
インポート宣言

### ISSUE THREAD

**Issue by SaitoAtsushi** [oitomo/r7rs-small-spec-ja#14]
7.1.7 に &lt;import 宣言&gt; という節がありますが、形式定義の中の他の節では &lt;インポート宣言&gt; というふうに片仮名書きになっています。 どちらに合わせるべきか微妙ですが統一すべきです。

**Comment by oitomo** [comment]
ご指摘ありがとうございます。
7.1.7 のほうを修正し、<インポート宣言> で統一しました。
