### ISSUE TITLE
一定時間

### ISSUE THREAD

**Issue by SaitoAtsushi** [oitomo/r7rs-small-spec-ja#15]
string-ref と string-set! についての説明に

> 一定時間で実行するための，この手続きへの要件はない。

とありますが、意味が把握し難いです。

条件無しで常に一定時間で実行できるかのようにも読めてしまいます。 原文が言おうとしていることは一定時間で実行できなくてもよいということなので「この手続きは一定時間で実行できる必要はない。」というような訳はいかがでしょうか。 R6RS では一定時間であることを要求していたので、微妙な表現だと R6RS と同じかと思ってしまいそうです。

用例を見ると、 "There is no requirement" の訳としては「必要はない」「要求しない」とするのは一般的なようです。
http://www.linguee.jp/%E8%8B%B1%E8%AA%9E-%E6%97%A5%E6%9C%AC%E8%AA%9E/%E7%BF%BB%E8%A8%B3/there+is+no+requirement+for.html

それとこれは間違いというわけではないのですが、技術文書では constant time は一定時間というよりも定数時間と訳すことが多いようです。  時間オーダーが O(1) であることをいうもので、実行時間が定まっているというのとはちょっとニュアンスが違う気がします。

**Comment by oitomo** [comment]
ご指摘ありがとうございます。確かに難解な訳でした。
「この手続きは定数時間で実行できる必要はない。」
としたいと思います。
